apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: "3.1.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    
    resources:
      limits:
        memory: 384Mi
      requests:
        cpu: 100m
        memory: 128Mi

    backgroundController:
      resources:
        limits:
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi

    cleanupController:
      resources:
        limits:
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi

    reportsController:
      resources:
        limits:
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi

    metricsServer:
      enabled: true

    admissionController:
      replicas: 1
      serviceMonitor:
        enabled: true