apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-pdns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-pdns
subjects:
- kind: ServiceAccount
  name: cert-manager-webhook-pdns-cert-manager-webhook-powerdns
  namespace: cert-manager