apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sys@thux.it
    privateKeySecretRef:
      name: letsencrypt-dns
    solvers:
    - dns01:
        webhook:
          groupName: acme.rancher.thux.it
          solverName: pdns
          config:
            # zone: example.com
            # zoneName: example.com
            apiUrl: https://api.ns.thux.it
            apiKeySecretRef:
            secretName: pdns-credentials
