apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-powerdns
  namespace: cert-manager
spec:
  interval: 24h
  url: https://lordofsystem.github.io/cert-manager-webhook-powerdns
