apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-pdns
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager-webhook-powerdns
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-powerdns
        namespace: cert-manager
  interval: 12h
  values:
    groupName: acme.rancher.thux.it