apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topo-system
spec:
  interval: 5m
  chart:
    spec:
      chart: topolvm
      version: "14.0.0"  # verifica che sia la versione corretta
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system
  install:
    createNamespace: true
  values:
    global:
      cattle:
        clusterId: c-m-slsmv4wq
        clusterName: thux
        rkePathPrefix: ""
        rkeWindowsPathPrefix: ""
        systemProjectId: p-r5kmr
        url: https://rancher.thux.it
    
    lvmd:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - postgresql
      deviceClasses:
      - default: true
        name: ssd
        spare-gb: 10
        volume-group: VG-topolvm
      - name: thin
        volume-group: VG-topolvm
        type: thin
        thin-pool:
          name: thinpool
          overprovision-ratio: 10.0
      tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: postgresql

    node:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - postgresql
      tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: postgresql