# base/infrastructure/storage/topolvm/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - storageclass.yaml
  - storageclass-thin.yaml