apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
  labels:
    prj: thux
spec:
  interval: 1h
  url: https://helm.traefik.io/traefik
