apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: traefik
  labels:
    prj: thux
spec:
  interval: 24h
  chart:
    spec:
      chart: traefik-crds
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
