apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrepo.yaml
- networkpolicy.yaml
- helmrelease.yaml
- helmrelease-crds.yaml
- traefik-config

configMapGenerator:
- name: traefik-helm-values
  namespace: traefik
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
