# base/infrastructure/descheduler/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: descheduler
spec:
  interval: 15m
  chart:
    spec:
      chart: descheduler
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  values:
    # Configurazione base comune
    kind: CronJob
    schedule: "*/30 * * * *"
    
    # DRY RUN di default - override negli overlay
    dryRun: true
    logLevel: "info"
    
    # USA IL CONFIGMAP per la policy
    deschedulerPolicyAPIVersion: "descheduler/v1alpha2"
    deschedulerPolicy: {}  # Vuoto, usa ConfigMap
    
    # Mount del ConfigMap
    configMapName: "descheduler"
    
    # Sicurezze base
    nodeSelector:
      kubernetes.io/os: linux
    
    # Non toccare nodi PostgreSQL
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "postgresql"
            operator: DoesNotExist
    
    # Pod critici
    ignorePvcPods: true
    evictSystemCriticalPods: false
    evictDaemonSetPods: false
    evictLocalStoragePods: false
    
    # Risorse conservative
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi