# base/postgres/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: pg-values-base
      valuesKey: values
    - kind: ConfigMap
      name: pg-values-overlay
      valuesKey: values
    - kind: Secret
      name: pg-credentials
      targetPath: backups.s3.accessKey
      valuesKey: ACCESS_KEY_ID
    - kind: Secret
      name: pg-credentials
      targetPath: backups.s3.secretKey
      valuesKey: SECRET_ACCESS_KEY
