# stg/postgres/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -thux-www
namespace: thux-www-2024
resources:
  - ../../../../base/postgres

  # - secrets.yaml    handled by hand
# base/postgres/network-policies/kustomization.yaml
configMapGenerator:
  - name: pg-values-overlay
    options:
      disableNameSuffixHash: true
    files:
      - values=./values-overlay.yaml  # usa il file locale
    behavior: replace  # importante: sostituisce il ConfigMap della base

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: cnpg
      spec:
        valuesFrom:
          - kind: ConfigMap
            name: pg-values-base-thux-www
            valuesKey: values
          - kind: ConfigMap
            name: pg-values-overlay-thux-www
            valuesKey: values
          - kind: Secret
            name: pg-credentials
            targetPath: backups.s3.secretKey
            valuesKey: S3_SECRET_KEY
    target:
      kind: HelmRelease
      name: cnpg
