apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-replicator
      version: "2.11.0"  
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
