# stg/postgres/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wikijs
resources:
  - ../../../../base/postgres

  # - secrets.yaml    handled by hand
# base/postgres/network-policies/kustomization.yaml
configMapGenerator:
  - name: pg-values-overlay
    options:
      disableNameSuffixHash: true
    files:
      - values=./values-overlay.yaml  # usa il file locale
    behavior: replace  # importante: sostituisce il ConfigMap della base

patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: cnpg
        labels:
          prj: thux
    target:
      kind: HelmRelease
      name: cnpg
